name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build PDF
      run:
        docker build resume .
        docker run resume
        mkdir CV_RESULT
        docker cp main.pdf CV_RESULT/main.pdf
