name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build PDF
      run:
        docker build .
    - name: running Docker
      run:
        docker run --name CV
        mkdir CV_RESULT
        docker cp CV:main.pdf CV_RESULT/main.pdf
        
