name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update_resume:
    runs-on: ubuntu-latest
    name: main.yml work
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - run: chmod +x main.sh
      - name: start action.yml
        uses: ./ # Uses an action in the root directory
        id: hello
      - run: ls -lah
      - run: git config --global user.email "anastasia.slabucho@gmail.com"
      - run: git config --global user.name "an-sla"
      
