name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_resume:
    runs-on: ubuntu-latest
    name: main.yml work
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: start action.yml
        uses: ./

      - run: git config --global user.email "anastasia.slabucho@gmail.com"
      - run: git config --global user.name "Anastasia Slabucho"
      - run: git checkout origin main index.html
      - run: git add resume.pdf
      - run: git add index.html
      - run: git status
      - run: git commit -m "resume.pdf and index.html"
      - run: git push origin HEAD:gh-pages --force # Committing pdf to new branch for GitHub Pages publication
      - run: git push origin HEAD:main --force
      
      - name: Publish pdf
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: resume_result
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      

