name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build PDF
      run:
        docker build --tag homework -f Dockerfile .
        docker run --name CV homework
        mkdir CV_RESULT
        docker cp CV:main.pdf CV_RESULT/main.pdf
        
