name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_resume:
    runs-on: ubuntu-latest
    name: main.yml work
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      - name: start action.yml
        uses: ./

      - run: git config --global user.email "anastasia.slabucho@gmail.com"
      - run: git config --global user.name "Anastasia Slabucho"
      - run: git add resume.pdf
      - run: git status
      - run: git commit -m "resume.pdf"

      - run: git push origin HEAD:main --force
      #- run: git request-pull v1.0 https://git.ko.xz/project master
      #- run: git rebase origin/main origin/pdf-page
      #- run: git checkout origin/main
      #- run: git merge origin/pdf-page
      

